name: Challenge 3 Pull test trigger

on:
  pull_request:
    types:
      - opened

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Challenge 3 Pull test
      run: echo "Will add code checks here in next challenge"
