name: Trigger development and production environments job

on:
  pull_request:
    branches:
      - main
jobs:
  dev-train-job:
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure ML Job
      run: az ml job create --file ./src/C5-dev-job.yml --resource-group rg-MLOps-Automation-090823 --workspace-name mlws-MLOps-Automation-090823

  prod-train-job:
    needs: dev-train-job
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure ML Job
      run: az ml job create --file ./src/C5-prod-job.yml --stream --resource-group rg-MLOps-Automation-090823 --workspace-name mlws-MLOps-Automation-090823   
